
project_id = "vtvlpphqcfektueuapeh"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true

[realtime]
enabled = true

[edge_functions]
[edge_functions.sendJobReminder]
verify_jwt = true

[edge_functions.updateWeatherCache]
verify_jwt = true

[edge_functions.stripeWebhook]
verify_jwt = false
