// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtvlpphqcfektueuapeh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0dmxwcGhxY2Zla3R1ZXVhcGVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyNjkwOTYsImV4cCI6MjA2MDg0NTA5Nn0.nlfeKa4T8JKWfVkM6rsT5mv2B2cg9LNwklmN591QIcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);